$(function(){bindPageEvent();$(".search_theme_list").each(function(index,items){var $item=$(items);if($item.find("dd").height()<55)
$item.siblings("a").hide();});$(window).scroll(function(){var scT,boxT,$search_nav;if(!$('.search_nav_box').length){return false;}
scT=$(document).scrollTop();boxT=$('.search_nav_box').offset().top;$search_nav=$('.search_nav');if(scT>boxT){$search_nav.css({'position':'fixed','top':0,'z-index':99,'background':'#fff'});}else{$search_nav.attr('style','');}});});$(".tags,.tagsback,.tags-orange").poptip({place:6});function bindPageEvent(){$("ul.search_nav li").bind("click",function(){var $this=$(this);var type=$.trim($this.find("a").text());if(type.indexOf("酒店")==0||type.indexOf("邮轮")==0)
return;$this.addClass("search_li").siblings().removeClass("search_li");});$(".xlesstime").each(function(index,items){var $item=$(items);if($item.find('p').height()>22){$item.find('.icon_arrow').show();$item.bind({"mouseover":function(){$(this).addClass("extra");},"mouseout":function(){$(this).removeClass("extra");}});}else{$item.find('.icon_arrow').hide();}});$("ul.pro_sort li").bind("click",function(){var $this=$(this);var index=$this.index();if($this.hasClass("sortLi"))
return;if(index==1||index==2)
$this.parent().next().find('.market_price').hide();else
$this.parent().next().find('.market_price').show();$this.addClass("sortLi").siblings().removeClass("sortLi");var $currentBox=$this.parentsUntil(".recommend").parent().find("div.pro_detail").hide().filter(":eq("+index+")").show();if(index==2)
{$currentBox.find(".all_ticket").hide();}});$("ul.hot_list li").bind("mouseover",function(){var $this=$(this);$this.addClass("hot_li").siblings().removeClass("hot_li");});$('.pro_list').hover(function(){$(this).addClass('pro_list_hover')},function(){$(this).removeClass('pro_list_hover');});$('.view-details').live('click',function(){$(this).parents('.pro_list').removeClass('list_bg');})
$(".js_goPage").bind("keyup",function(e){var page=$(this).val();if(!page)
return;switch(e.which){case 13:goPage(page);break;}});$(".js_Morecity_btn").toggle(function(){$(this).html('收起<i class="arrow_up"></i>').parent().find('.search_theme_list').addClass("search_more");},function(){$(this).html('更多<i class="arrow"></i>').parent().find('.search_theme_list').removeClass("search_more");});$(".all_ticket").bind("click",function(){var $this=$(this);var $dl=$this.siblings("dl");var count=$dl.length;var status=$this.attr("showall")?true:false;if(status){$dl.hide();$dl.filter(":lt(3)").show();$this.removeAttr("showall");$this.html("展开全部门票（"+count+"）<i class='arrow'></i>");}else{$dl.show();$this.attr("showall","true");$this.html("收起全部门票（"+count+"）<i class='arrow_up'></i>");}});$(".other-info").hover(function(){$(this).addClass("tq_hover");},function(){$(this).removeClass("tq_hover");});}
(function(){localFunSearchDown();function localFunSearchDown(){var $search_sub=$('.search_sub');var $oLi=$search_sub.find('li');var oHover=false;if(!$search_sub.length){return false;}
$oLi.each(function(){var $me=$(this);var $moretravel=$me.children('.moretravel');var l=$search_sub.offset().left;if($moretravel.length){$moretravel.css({left:l-$me.offset().left});}});$oLi.hover(function(){oHover=true;$(this).addClass('active').siblings().removeClass('active');},function(){oHover=false;setTimeout(function(){if(!oHover){$oLi.removeClass('active');}},200);});}})();$(function(){var $document=$(document);$(".common_diqu_list").first().addClass("active");(function(){var $searchTitle=$(".search-title");var $searchMore=$(".search-more");var $searchMoreDropdown=$(".search-more-dropdown");$document.on("click",function(e){var $target=$(e.target);var $parent=$target.parents(".search-more");if(($target.is(".search-title")||$target.parents(".search-title").length>0)&&$searchMore.is(".active")){$searchMore.removeClass("active");}else if($target.is(".search-more")||$parent.length>0){$searchMore.addClass("active");}else{$searchMore.removeClass("active");}});$document.on("mouseenter",".search-more",function(){$searchMore.addClass("active");});$document.on("mouseleave",".search-more",function(){$searchMore.removeClass("active");});$searchMoreDropdown.on("click","a",function(e){var $this=$(this);var value=$this.attr("data-value");var text=$this.text();$searchTitle.find("span").text(text);if(value==="TRAFFIC_AND_SERVES"){$searchTitle.addClass("pink");}else{$searchTitle.removeClass("pink");}
e.stopPropagation();$searchMore.removeClass("active");});})();})
;$(function(){$('.common_diqu_list').click(function(){$(this).addClass('active').siblings().removeClass('active');});});function addLosc(elem,loscid){elem.find('a').each(function(){var $This=$(this),$herf=$This.attr('href');$This.attr('href',$herf+'?losc='+loscid+'&ict=i');});}